name: Build and Push to VM Registry

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: my-runner-set
    steps:
      # Используем checkout (он работает через git, докер ему не нужен)
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Kaniko Binary
        run: |
          # Скачиваем в /tmp
          curl -sSL -o /tmp/kaniko-executor https://github.com
          chmod +x /tmp/kaniko-executor

          # Запускаем, указывая кастомные директории, чтобы не лезть в корень /
          /tmp/kaniko-executor \
            --context "${{ github.workspace }}" \
            --dockerfile "${{ github.workspace }}/Dockerfile" \
            --destination "51.250.79.226:5000/my-app:${{ github.sha }}" \
            --insecure \
            --skip-tls-verify \
            --cache=false \
            --rootless