name: Build and Push to Local Registry

on:
  push:
    branches: [ dev ]

jobs:
  build:
    # Имя должно СТРОГО совпадать с name релиза в helmfile (arc-runner-set)
    runs-on: arc-runner-set

    # Переменная, чтобы Docker-клиент внутри раннера видел контейнер dind
    env:
      DOCKER_HOST: tcp://localhost:2375

    steps:
      - name: Build image
        run: |
          # Собираем как обычно
          docker build -t my-app-local .
          
          # Явно вешаем теги для нашего реестра
          docker tag my-app-local registry-service.arc-systems.svc.cluster.local:5000/my-app:${{ github.sha }}
          docker tag my-app-local registry-service.arc-systems.svc.cluster.local:5000/my-app:latest

      - name: Push to Local Registry
        run: |
          # Теперь пушим именно те теги, которые создали выше
          docker push registry-service.arc-systems.svc.cluster.local:5000/my-app:${{ github.sha }}
          docker push registry-service.arc-systems.svc.cluster.local:5000/my-app:latest
