name: Build and Push to VM Registry

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: my-runner-set 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: my-app
          tag: ${{ github.sha }}
          registry: 51.250.79.226:5000
          insecure: true
          # Это заставит экшен использовать бинарник, а не docker run
          extra_args: "--skip-tls-verify" 